### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by stefanhk31** [stefanhk31/dart-class-name-updater#26]
Now that I'm not just tinkering around to see what works, it's time we be good little programmers and make some proper test coverage. 

This issue will be for adding tests to _existing_ code in main (as of commit 861014cd).

All subsequent tickets should have an assumed testing requirement to them.

**Comment by stefanhk31** [comment]
Resource: https://code.visualstudio.com/api/working-with-extensions/testing-extension

**Comment by markclemons** [comment]
I like the start. If we can't fill in the test right now,  I would put an assert.equals(true, false) into each empty test so they fail, and then come up with the way to implement the test.

**Comment by markclemons** [comment]
- You need a test for excludedFolders that has a .gitignore file and adds the stuff inside appropriately
- You need a test for excludedFolders that has an empty worksspace and expects an empty list to come back []
